### ISSUE TITLE
Inconsistent behavior between 0.6.2 and 0.6.3 on node.js

### ISSUE THREAD

**Issue by trieloff** [funcool/httpurr#16]
I'm experiencing an issue in the node.js client that I am struggling to track down. The code in question can be found here: https://github.com/trieloff/openwhisk-cljs/tree/lumo

I'm on node.js v7.10.0 on macOS and I try to make an HTTP GET request to the StackOverflow API, which I will then decompress using zlib (StackOverflow conveniently compresses all responses, even if you did not ask for it) and then parse the JSON for further processing.

For smaller responses, everything works fine, but when the response size exceeds roughly one kilobyte, I'm getting errors. I have tried upgrading to the current master version (I will refer to it as 0.6.3)

# On 0.6.2
```bash
$ node ./test.js ./main.js url=http://stackoverflow.com/questions/43755892/in-golang-how-to-deal-with-unknown-variables-or-how-to-deal-with-multiple-datab/43841502 key="XXXXXXXXXXXXXX"
907 1395
{"items":[{"owner":{"reputation":5…
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at openwhisk_cljs.core.gzjson (/Users/trieloff/Code/openwhisk-cljs/main.js:2202:85)
    at /Users/trieloff/Code/openwhisk-cljs/main.js:2213:299
    at /Users/trieloff/Code/openwhisk-cljs/main.js:1994:248
    at r (/Users/trieloff/Code/openwhisk-cljs/main.js:44:7722)
    at i._settlePromiseFromHandler (/Users/trieloff/Code/openwhisk-cljs/main.js:43:13044)
    at i._settlePromise (/Users/trieloff/Code/openwhisk-cljs/main.js:43:13847)
    at i._settlePromise0 (/Users/trieloff/Code/openwhisk-cljs/main.js:43:14548)
    at i._settlePromises (/Users/trieloff/Code/openwhisk-cljs/main.js:43:15878)
    at r._drainQueue (/Users/trieloff/Code/openwhisk-cljs/main.js:42:3008)
    at r._drainQueues (/Users/trieloff/Code/openwhisk-cljs/main.js:42:3069)
    at Immediate.drainQueues (/Users/trieloff/Code/openwhisk-cljs/main.js:42:1098)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
905 1782
{"items":[{"tags":["go"],"o…
```
The reported length according to the `Content-Length` header is 1782 bytes, but the length of the `:body` `Buffer` is only 905 bytes – it varies from invocation to invocation. It looks like only the first chunk is coming along, which should have been fixed in 2de60b562ec15abadf06ccfd241cd0ec71e2240c

This is why I upgraded to the current `master` version.

# On 6.3.2
```bash
$ node ./test.js ./main.js url=http://stackoverflow.com/questions/43755892/in-golang-how-to-deal-with-unknown-variables-or-how-to-deal-with-multiple-datab/43841502 key="XXXXXXXXXXXXXX"
1725 1783
{ Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:355:17)
    at Gunzip.Zlib._processChunk (zlib.js:526:30)
    at zlibBufferSync (zlib.js:225:17)
    at Object.exports.gunzipSync (zlib.js:161:10)
    at openwhisk_cljs.core.gunzip (/Users/trieloff/Code/openwhisk-cljs/main.js:2198:593)
    at openwhisk_cljs.core.gzjson (/Users/trieloff/Code/openwhisk-cljs/main.js:2199:118)
    at /Users/trieloff/Code/openwhisk-cljs/main.js:2201:395
    at /Users/trieloff/Code/openwhisk-cljs/main.js:1993:702
    at r (/Users/trieloff/Code/openwhisk-cljs/main.js:44:9004)
    at i._settlePromiseFromHandler (/Users/trieloff/Code/openwhisk-cljs/main.js:43:14217)
    at i._settlePromise (/Users/trieloff/Code/openwhisk-cljs/main.js:43:15020)
    at i._settlePromise0 (/Users/trieloff/Code/openwhisk-cljs/main.js:43:15721)
    at i._settlePromises (/Users/trieloff/Code/openwhisk-cljs/main.js:43:17051)
    at r._drainQueue (/Users/trieloff/Code/openwhisk-cljs/main.js:42:2916)
    at r._drainQueues (/Users/trieloff/Code/openwhisk-cljs/main.js:42:2977)
    at Immediate.drainQueues (/Users/trieloff/Code/openwhisk-cljs/main.js:42:1098) errno: -3, code: 'Z_DATA_ERROR' }
```

The size mismatch between `Content-Length` (1783) and `Buffer.length` (1725) is much smaller, but it is still notable. Additionally, it looks like either the first part of the body is cut off or I'm seeing some encoding problem, because zlib is failing with an `incorrect header check`.

Ideally, the decompression should be handled transparently in the client, but I have not been able to translate the example from [node's zlib documentation](https://nodejs.org/api/zlib.html#zlib_compressing_http_requests_and_responses) to ClojureScript.

**Comment by trieloff** [comment]
I've provided a test case in #17
